README
======

Copyright (c) 2011, Aaron Christianson  ninjaaron@gmail.com

Licensed under the OFL v1.1

'bitocra' is a small, clear bitmap font especially for viewing a lot of
lines of code or other text at once.  It is somewhat stylized after the
old OCR-A font, with many changes due to the format and size. It has all
iso-8859-1 characters

'bitocrafull' is the same basic font, with extensive support for Latin
unicode characters.  Many of the characters in Latin Extended-A
(primarily characters used in Eastern European languages as well as some
others)  are experimental, as I don't use them, and need confirmation
from someone more used to them as to their correctness.  Any input in 
this area is welcome.


Others
------
* 'bitocra13' is a much-requested larger version of bitocra.  It currently 
supports ISO8859 encoding.

* 'bitocra7' is a never-requested smaller version of bitocra.  It is
currently only ascii, but will be expanded to ISO8895.

* '4thD' is a 4px font that I made for fun with complete ascii 128
encoding.  It may, one day, evolve into the 5thD.


Introducing bitbuntu!
~~~~~~~~~~~~~~~~~~~~~
* 'bitbuntu' and 'bitbuntufull' are fonts in the spirit of the Ubuntu font
family with the metrics and default charsets of their bitocra
counterparts.  This font seems to be quite popular, and may soon recieve
it's own repository.


Install instructions
--------------------

In some distros, you can simply extract the archive to you `~/.fonts`
folder, or `/usr/share/fonts` (or one of it's subdirectories) if you want
it to be available to all users.  After that, update your font cache
with:

..............
$ fc-cache -fv
..............

And restart your X session.

If you want to add it to your X core fonts, you will need to move to the
directory and run `mkfontdir`, add the directory to your X fontpath:

........................
$ xset +fp /path/to/font
$ xset fp rehash
........................

This will enable it for your session.  You can make it perminant by
adding the path to `/etc/X11/xorg.conf` if you have it.  If you do don't
(like most people, now that Xorg configures automatically), set the
above commands to run with autostart scripts, `~/.xinitrc`, or Startup
Applications, depending on your WM/DE/DM situation.


If it still doesn't work
~~~~~~~~~~~~~~~~~~~~~~~~

In Debian, Ubuntu, Fedora, and possibly other distros, bitmap fonts are
disabled by default. This can be fixed by running the following command:
In the folder `/etc/fonts/conf.d/`, there is usually a file responsible
for this.  In Debian and it's derivatives, it's something like
`70-no-bitmap-fonts`.  In Fedora, I think it was in the 20's, maybe
`25-no-bitmaps-fedora`.  It's something obvious.

Also -in DEBIAN ONLY-
you can run:

....................................
# dpkg reconfigure fontconfig-config
# dpkg reconfigure fontcofig
....................................

The first command will open a little ncurses thing where you can turn on
the bitmap fonts.  After that, the above directions ought to work.
